#pragma once

#include <engine/graphics/resources/model.h>

#include <cstdint>

//==============================================================================
namespace std
{

inline std::size_t hash<nc::ModelHandle>::operator()(const nc::ModelHandle& handle) const
{
  // hash_combine lambda was generated by deepseek ai
  auto hash_combine = []<typename T>(std::size_t& seed, const T& value)
  {
    std::hash<T> hasher;
    seed ^= hasher(value) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
  };

  std::size_t seed = 0;
  hash_combine(seed, handle.m_model_id);
  hash_combine(seed, handle.m_lifetime);
  return seed;
}

}
